language: groovy
jdk:
- oraclejdk7
branches:
  only:
  - master
  - /^sprint\d+$/
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5 # give xvfb some time to start
  - run-app  # start a Web server
  - sleep 10 # give Web server some time to bind to sockets, etc
before_install:
  - openssl aes-256-cbc -K $encrypted_013b5f06e15b_key -iv $encrypted_013b5f06e15b_iv -in sonar-secret.txt.enc -out sonar-secret.txt -d
  - mv sonar-secret.txt /home/travis/
  - wget http://repo1.maven.org/maven2/org/codehaus/sonar/runner/sonar-runner-dist/2.4/sonar-runner-dist-2.4.zip
  - unzip sonar-runner-dist-2.4.zip
  - rm sonar-runner-dist-2.4.zip
  - sudo mv sonar-runner-2.4 /opt/sonar-runner
  - sudo rm /opt/sonar-runner/conf/sonar-runner.properties
  - sudo mv sonar-runner.properties /opt/sonar-runner/conf/
  - export SONAR_RUNNER_HOME=/opt/sonar-runner
  - export PATH=$PATH:$SONAR_RUNNER_HOME/bin
script:
  - ./grailsw refresh-dependencies
  - ./grailsw "test-app -echoOut -echoErr -coverage -xml"
after_success:
  - ./grailsw codenarc
  - ./grailsw coveralls
  - sonar-runner
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: heroku
  api_key:
    secure: djGlUrhKZ7AYRhap9X34FKkH6Nr4QnsAiVIXgnUetO87iez10/RYvYegpQfaf+FubJjkH/zrrxU4WldBfSI96rJjHjBiT0sR5z06ZwPaq0lhLcbRrZO1axQBEk/Xuo79L8nG0joBs+hx/gGU62uZ+DjcZbzsoUCauBRtpuAq3URrJjLatpemvSJGy5HCmMmM9ZQnXOvQFHIWAL0B54ozTQsBznrga2cAqa+PJ8sEYxYM9XjiCxr1MxDrfA3bhjaRR7iUG1nUihauIiiKOvO0OEf+Of3Pj+4l3Qt1l39E4sXs3GipOdL0m7gb53H1IO7XfT6qqN4WCIRs2iIoX3YDtR4i8ZJEcYm1hB1a2BB5MlZLJyOtjlUBP7hyxzPuO4bxClzNpnux6EvfKxBsQnFMZIs92dN3kuIzTehW6maVJT5K+xzOeDgwAWIcxN6uyD/lwulvulu4ARGr6DUVMe+IRnmHHkzWjmwJU+PTvwsYSLKxnKZ9fE5gI76BUrFebdikuH/pCmcHB77EJhktqEAZTldEhfyVbqCitcFTUZjwxjWHAiZVkLg8XJiiSzHDZ5V2rDEOATU1glqlEy/fEumsz/PDL4XJ45dmM/9qzUg+3mhtudzZlNLrAb/Mcz0UKP/eiAt1GXE9ZUHy+BaYF18Elex5GRhSYN08MEdSmdCJNpQ=
  app: fishandfriends
  on:
    repo: FishAndFriends/FishAndFriends
    all_branches: true
