language: groovy
jdk:
- oraclejdk7
branches:
  only:
  - master
script: ./grailsw refresh-dependencies && ./grailsw "test-app unit:" && ./grailsw refresh-dependencies && ./grailsw "test-app functional:"
deploy:
  provider: heroku
  api_key:
    secure: djGlUrhKZ7AYRhap9X34FKkH6Nr4QnsAiVIXgnUetO87iez10/RYvYegpQfaf+FubJjkH/zrrxU4WldBfSI96rJjHjBiT0sR5z06ZwPaq0lhLcbRrZO1axQBEk/Xuo79L8nG0joBs+hx/gGU62uZ+DjcZbzsoUCauBRtpuAq3URrJjLatpemvSJGy5HCmMmM9ZQnXOvQFHIWAL0B54ozTQsBznrga2cAqa+PJ8sEYxYM9XjiCxr1MxDrfA3bhjaRR7iUG1nUihauIiiKOvO0OEf+Of3Pj+4l3Qt1l39E4sXs3GipOdL0m7gb53H1IO7XfT6qqN4WCIRs2iIoX3YDtR4i8ZJEcYm1hB1a2BB5MlZLJyOtjlUBP7hyxzPuO4bxClzNpnux6EvfKxBsQnFMZIs92dN3kuIzTehW6maVJT5K+xzOeDgwAWIcxN6uyD/lwulvulu4ARGr6DUVMe+IRnmHHkzWjmwJU+PTvwsYSLKxnKZ9fE5gI76BUrFebdikuH/pCmcHB77EJhktqEAZTldEhfyVbqCitcFTUZjwxjWHAiZVkLg8XJiiSzHDZ5V2rDEOATU1glqlEy/fEumsz/PDL4XJ45dmM/9qzUg+3mhtudzZlNLrAb/Mcz0UKP/eiAt1GXE9ZUHy+BaYF18Elex5GRhSYN08MEdSmdCJNpQ=
  app: fishandfriends
  on:
    repo: FishAndFriends/FishAndFriends
